INSERT INTO COURIER (NOMBRE, COSTO_POR_PESO, REGION_REPARTE)
values ('Blue', 1000, 'c');
INSERT INTO COURIER (NOMBRE, COSTO_POR_PESO, REGION_REPARTE)
values ('Starken', 1500, 'b');
INSERT INTO COURIER (NOMBRE, COSTO_POR_PESO, REGION_REPARTE)
values ('ChileExpress', 1200, 'a');
COMMIT;